name: Generate VERSION.md

on:
  release:
    types: [published]

jobs:
  test:
    name: Generate VERSION.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mitre-saf
        uses: actions/checkout@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Get information for VERSION.md
        run: |
          git pull origin dev#v2
          echo "**Release:** " > VERSION.md
          git describe --tags $(git rev-list --tags --max-count=1) >> VERSION.md
          git describe --tags $(git rev-list --tags --max-count=1) > VERSION
          echo "<br><br>**Date:** " >> VERSION.md
          git show -s --format=%ci $(git rev-list --tags --max-count=1) >> VERSION.md
          echo "<br><br>**Commit:** " >> VERSION.md
          git rev-list --tags --max-count=1 >> VERSION.md
      - name: Commit and push changes to VERSION.md
        uses: github-actions-x/commit@v2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "dev#v2"
          commit-message: "Publish version information"
          force-add: "true"
        env:
          CI: true
